version: '3'

services:
  database-service:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book_club
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  clubservice:
    depends_on:
      - database-service
    build: .
    ports:
      - "9999:9999"
